<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>step03</artifactId>
    <groupId>no.maddin.api-handling</groupId>

    <parent>
        <groupId>no.maddin</groupId>
        <artifactId>api-handling</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>no.maddin</groupId>
            <artifactId>test-tools</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>executable-jar</id>
                        <goals>
                            <goal>build-info</goal>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>get-oas</id>
                        <goals><goal>copy</goal></goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>no.maddin.api-handling</groupId>
                                    <artifactId>step02</artifactId>
                                    <classifier>openapi</classifier>
                                    <version>${project.version}</version>
                                    <type>yaml</type>
                                </artifactItem>
                            </artifactItems>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.openapiprocessor</groupId>
                <artifactId>openapi-processor-maven-plugin</artifactId>
                <version>2024.1</version>
                <configuration>
                    <id>spring</id>
                    <apiPath>${project.build.directory}/dependency/step02-openapi.yaml</apiPath>
                    <options>
                        <values>
                            <targetDir>${project.basedir}/target/generated-sources/spring</targetDir> <!-- can be removed when version > 2024.1 is released -->
                            <mapping>${project.basedir}/src/api/mapping.yaml</mapping>
                            <showWarnings>true</showWarnings>
                        </values>
                    </options>
                </configuration>
                <executions>
                    <execution>
                        <id>process</id>
                        <phase>generate-sources</phase>
                        <goals><goal>process</goal></goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>io.openapiprocessor</groupId>
                        <artifactId>openapi-processor-spring</artifactId>
                        <version>2025.4</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>

